### PR TITLE
WIP: Add contentHeaders fetch-Parameter

### PR DESCRIPTION
**Pull request by DracoBlue**

### CODE REVIEW

**Comment by aFarkas** [comment]
@DracoBlue 
What about allowing to modify all xhr options?

This would look something like this:

```js
/*  ....  */

static get defaults(){
    return {
        xhrOptions: null,
    };
}

/*  ....  */
this._xhr = rb.fetch(options.contentUrl, options.xhrOptions).then(this._addContent);
```

**Comment by DracoBlue** [comment]
Good idea!

Alexander Farkas <notifications@github.com> schrieb am Fr. 20. Jan. 2017 um
13:10:

**Comment by aFarkas** [comment]
Are you gonna to update your PR or should I simply make the change?

**Comment by DracoBlue** [comment]
If you can change that on your own, would be nice!

Alexander Farkas <notifications@github.com> schrieb am Fr. 20. Jan. 2017 um
19:08:

**Comment by DracoBlue** [comment]
Thank you!

**Pull request closed without merging**
